kind: pipeline
name: pr-sonarcloud

steps:
 - name: build-maven
   image: maven:3.6.2-jdk-11
   commands:
   - mvn install --batch-mode
   - mvn verify sonar:sonar -Dsonar.login=371a5188195e16a5b9838856c9090718f6ce0089 -Dsonar.pullrequest.provider=GitHub -Dsonar.pullrequest.key=${DRONE_PULL_REQUEST} -Dsonar.pullrequest.branch=comment -Dsonar.pullrequest.github.repository=${DRONE_REPO}
  
trigger:
  event:
  - pull_request
