kind: pipeline
name: pr-sonarcloud

steps:
- name: build-maven
  image: maven:3.6.2-jdk-11
  commands:
  - ls 
  
- name: step1
  image: maven:3.6.2-jdk-11
  commands:
  - ls  
  depends_on:
  - build-maven
  
- name: step11
  image: maven:3.6.2-jdk-11
  commands:
  - ls  
  depends_on:
  - build-maven
  
- name: step2
  image: maven:3.6.2-jdk-11
  commands:
  - ls  
  depends_on:
  - build-maven  
  
- name: step22
  image: maven:3.6.2-jdk-11
  commands:
  - ls  
  depends_on:
  - build-maven  
  
- name: step22
  image: maven:3.6.2-jdk-11
  commands:
  - ls  

- name: step23
  image: maven:3.6.2-jdk-11
  commands:
  - ls  

- name: step24
  image: maven:3.6.2-jdk-11
  commands:
  - ls  


- name: step25
  image: maven:3.6.2-jdk-11
  commands:
  - ls  
  
trigger:
  event:
  - pull_request
