kind: pipeline
name: pr-sonarcloud

steps:
- name: build-maven
  image: maven:3.6.2-jdk-11
  commands:
  - ls -ltra
  - echo $DRONE_COMMIT
  - echo $DRONE_COMMIT_BRANCH
  - echo $DRONE_COMMIT_LINK
  - echo $DRONE_COMMIT_MESSAGE
  - echo $DRONE_COMMIT_REF
  - echo $DRONE_COMMIT_SHA
  - DRONE_COMMIT_REF=refs/pull/7/head
  - echo $DRONE_COMMIT
  - echo $DRONE_COMMIT_BRANCH
  - echo $DRONE_COMMIT_LINK
  - echo $DRONE_COMMIT_MESSAGE
  - echo $DRONE_COMMIT_REF
  - echo $DRONE_COMMIT_SHA
   
trigger:
  event:
  - pull_request
