kind: pipeline
name: pr-sonarcloud

steps:
- name: build-maven
  image: maven:3.6.2-jdk-11
  commands:
  - mvn install --batch-mode
  
- name: sonar
  image: maven:3.6.2-jdk-11
  commands:
  - mvn verify sonar:sonar
  depends_on:
  - build-maven
  
trigger:
  event:
  - pull_request
