---
kind: pipeline
name: pr-test-sonarcloud

node:
  instance: highmemory
  
platform:
  os: linux
  arch: amd64

steps:

- name: build-maven
  image: maven:3.6.2-jdk-11
  commands:
  - mvn clean install --batch-mode
