kind: pipeline
name: default

steps:
- name: build-maven 
  image: maven:3.6.2-jdk-11
  commands:
  - mvn clean install --batch-mode

- name: sonar
  image: mvn
  commands:
  - mvn verify sonar:sonar
  environment:
    MAVEN_OPTS: -Xmx512m
  depends_on:
  - build-maven

trigger:
  event:
  - pull_request
