kind: pipeline
name: pr-sonarcloud1

steps:
- name: smoke-test
  image: maven:3.6.2-jdk-11
  commands:
  - echo "mahesh testing" 
  - sleep 5
  
- name: build-maven-test1
  image: maven:3.6.2-jdk-11
  commands:
  - echo "mahesh testing" 
  - sleep 5

- name: build-maven-test2
  image: maven:3.6.2-jdk-11
  commands:
  - echo "mahesh testing" 
  - sleep 5
  
- name: build-maven-test3
  image: maven:3.6.2-jdk-11
  commands:
  - echo "mahesh testing" 
  - sleep 5 
  
- name: build-maven-test4
  image: maven:3.6.2-jdk-11
  commands:
  - echo "mahesh testing" 
  - sleep 5  

  depends_on: 
  - build-maven-test1
  - build-maven-test2
  - build-maven-test3

trigger:
  event:
  - pull_request  
