---
kind: pipeline
name: pr-test-sonarcloud

node:
  instance: highmemory
  
platform:
  os: linux
  arch: amd64

steps:

- name: build-maven
  image: maven:3-jdk-10
  commands:
  - mvn clean install --batch-mode

- name: sonar
  image: maven:3-jdk-10
  commands:
  - mvn verify sonar:sonar
  environment:
    MAVEN_OPTS: -Xmx512m
  depends_on:
  - build-maven

trigger:
  event:
  - pull_request
