kind: pipeline
name: pr-sonarcloud

steps:
- name: build-maven
  image: maven:3.6.2-jdk-11
  commands:
  - ls 
  
- name: step1
  image: maven:3.6.2-jdk-11
  commands:
  - ls  
  
- name: step2
  image: maven:3.6.2-jdk-11
  commands:
  - ls  
  
- name: step11
  image: maven:3.6.2-jdk-11
  commands:
  - ls  

- name: step22
  image: maven:3.6.2-jdk-11
  commands:
  - ls  
- depends_on
    - build-maven
    - step1
    - step2
  
   
trigger:
  event:
  - pull_request
